# -*- coding: utf-8 -*-
"""FiltrosLineares_Modificado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QFQW_EjOl9iG1RgvldtqBRZWP8piw-u

# Filtros lineares
"""

import matplotlib.pyplot as plt
import numpy as np
from skimage import data
from skimage.color import rgb2gray

# Função gera ruído do notebook anterior
def gera_ruido(original, noise_type="gaussian", noise_level=0.02):
    # Verifica se a imagem é nível de cinzas
    if len(original.shape) == 3:
        grayscale = rgb2gray(original)
    else:
        grayscale = original

    # --- Adiciona ruído gaussiano, ou sal e pimenta ---
    if noise_type == "gaussian":
        noise = np.random.normal(0, noise_level, grayscale.shape)
        grayscale_ruido = grayscale + noise
    else: # "salt_pepper"
        grayscale_ruido = grayscale.copy()
        p = noise_level  # fração de pixels afetados

        # máscaras aleatórias
        rnd = np.random.rand(*grayscale.shape)
        grayscale_ruido[rnd < p / 2] = 0      # pimenta
        grayscale_ruido[rnd > 1 - p / 2] = 1  # sal

    # Garante faixa dinâmica válida
    grayscale_ruido = np.clip(grayscale_ruido, 0, 1)
    return(grayscale_ruido)

def main():
  # Carrega uma imagem
  original_image = data.camera()

  # Normaliza para 0-1
  grayscale_original = original_image / 255.0

  # Gera ruído sal e pimenta
  noisy_image_sp = gera_ruido(grayscale_original, noise_type="salt_pepper", noise_level=0.1)

  # Vamos escolher uma linha
  row_index = 100

  # Extrai a linha das imagens com e sem ruído
  originalRow = grayscale_original[row_index, :]
  noisyRow = noisy_image_sp[row_index, :]

  # Plot the pixel intensities of the selected rows
  plt.figure(figsize=(12, 5))
  plt.plot(originalRow, label='Linha Original', color='blue')
  plt.plot(noisyRow, label='Linha com Ruído Sal e Pimenta', color='red', alpha=0.7)
  plt.title(f'Comparação de Intensidade de Pixels na Linha {row_index}')
  plt.xlabel('Coluna de Pixel')
  plt.ylabel('Intensidade de Pixel (Normalizada)')
  plt.legend()
  plt.grid(True)
  plt.show()

  # Display the full images for context (optional)
  plt.figure(figsize=(12, 6))

  plt.subplot(1, 2, 1)
  plt.imshow(grayscale_original, cmap='gray')
  plt.axhline(y=row_index, color='r', linestyle='-') # Highlight the selected row
  plt.title('Imagem Original (Grayscale)')
  plt.axis('off')

  plt.subplot(1, 2, 2)
  plt.imshow(noisy_image_sp, cmap='gray')
  plt.axhline(y=row_index, color='r', linestyle='-') # Highlight the selected row
  plt.title('Imagem com Ruído Sal e Pimenta')
  plt.axis('off')

  plt.tight_layout()
  plt.show()

main()

"""# Exercício: Implemente uma função que aplique o filtro da média para um kernel de 3 pontos. Sua função deve receber uma linha de uma imagem e retornar uma nova linha com o resultado do filtro da média de três pontos."""

import matplotlib.pyplot as plt
import numpy as np

def filtroMedia3pontos(rowData):
    # Cria uma cópia do tipo float para guardar o resultado
    # dica, use np.copy
    resultado = np.copy(rowData).astype(float)

    # Aplique o filtro da média usando for
    # Dica, comece do segundo até o penúltimo elemento do vetor
    for i in range(1, len(rowData) - 1):
        # Média aritmética simples entre o anterior, o atual e o próximo
        media = (rowData[i-1] + rowData[i] + rowData[i+1]) / 3.0
        resultado[i] = media
    return resultado


# Faça uma função main que chame a função criada para cinco
# linhas arbitrárias e retorne o resultado


# Para cada linha, apresente o gráfico como no exemplo acima
def main():
    # 1. Carrega e prepara a imagem
    original_image = data.camera()
    grayscale_original = original_image / 255.0

    # 2. Gera ruído sal e pimenta (10%)
    noisy_image = gera_ruido(grayscale_original, noise_type="salt_pepper", noise_level=0.1)

    # 3. Escolhe 5 linhas arbitrárias
    linhas_indices = [50, 150, 250, 350, 450]

    # 4. Processa e plota cada linha
    for idx, row_idx in enumerate(linhas_indices):
        noisy_row = noisy_image[row_idx, :]
        filtered_row = filtroMedia3pontos(noisy_row)

        plt.figure(figsize=(12, 4))
        plt.plot(noisy_row, label='Linha com Ruído', color='red', alpha=0.4)
        plt.plot(filtered_row, label='Linha Filtrada (Média 3pts)', color='blue', linewidth=1.5)

        plt.title(f'Resultado do Filtro na Linha {row_idx}')
        plt.xlabel('Coluna (Pixel)')
        plt.ylabel('Intensidade')
        plt.legend(loc='upper right')
        plt.grid(True, linestyle='--', alpha=0.6)
        plt.tight_layout()
        plt.show()

        # --- Visualização 2:
        plt.figure(figsize=(12, 5))

        # Imagem Original
        plt.subplot(1, 2, 1)
        plt.imshow(grayscale_original, cmap='gray')
        plt.axhline(y=row_idx, color='r', linestyle='-') # Linha indicadora
        plt.title(f'Original (Linha {row_idx} destacada)')
        plt.axis('off')

        # Imagem com Ruído
        plt.subplot(1, 2, 2)
        plt.imshow(noisy_image, cmap='gray')
        plt.axhline(y=row_idx, color='r', linestyle='-') # Linha indicadora
        plt.title(f'Com Ruído (Linha {row_idx} destacada)')
        plt.axis('off')

        plt.tight_layout()
        plt.show()
# Chama a função principal
main()

"""Exercício: Repita o exercício para um kernel de cinco pontos."""

def filtroMedia5pontos(rowData):
    # Cria uma cópia do tipo float para guardar o resultado
    resultado = np.copy(rowData).astype(float)

    # Aplique o filtro da média usando for para 5 pontos
    # Começa do terceiro (índice 2) até o antepenúltimo (len - 2)
    for i in range(2, len(rowData) - 2):
        # Média de 5 pontos: [i-2, i-1, i, i+1, i+2]
        soma = rowData[i-2] + rowData[i-1] + rowData[i] + rowData[i+1] + rowData[i+2]
        resultado[i] = soma / 5.0

    return resultado

def main():
    # 1. Carrega e prepara a imagem
    original_image = data.camera()
    grayscale_original = original_image / 255.0

    # 2. Gera ruído sal e pimenta (10%)
    noisy_image = gera_ruido(grayscale_original, noise_type="salt_pepper", noise_level=0.1)

    # 3. Escolhe 5 linhas arbitrárias
    linhas_indices = [50, 150, 250, 350, 450]

    # 4. Processa e plota cada linha
    for idx, row_idx in enumerate(linhas_indices):
        noisy_row = noisy_image[row_idx, :]
        filtered_row = filtroMedia5pontos(noisy_row)

        plt.figure(figsize=(12, 4))
        plt.plot(noisy_row, label='Linha com Ruído', color='red', alpha=0.4)
        plt.plot(filtered_row, label='Linha Filtrada (Média 5pts)', color='blue', linewidth=1.5)

        plt.title(f'Resultado do Filtro na Linha {row_idx}')
        plt.xlabel('Coluna (Pixel)')
        plt.ylabel('Intensidade')
        plt.legend(loc='upper right')
        plt.grid(True, linestyle='--', alpha=0.6)
        plt.tight_layout()
        plt.show()


        # --- Visualização 2:
        plt.figure(figsize=(12, 5))

        # Imagem Original
        plt.subplot(1, 2, 1)
        plt.imshow(grayscale_original, cmap='gray')
        plt.axhline(y=row_idx, color='r', linestyle='-') # Linha indicadora
        plt.title(f'Original (Linha {row_idx} destacada)')
        plt.axis('off')

        # Imagem com Ruído
        plt.subplot(1, 2, 2)
        plt.imshow(noisy_image, cmap='gray')
        plt.axhline(y=row_idx, color='r', linestyle='-') # Linha indicadora
        plt.title(f'Com Ruído (Linha {row_idx} destacada)')
        plt.axis('off')

        plt.tight_layout()
        plt.show()

        # --- Visualização 2
        plt.figure(figsize=(12, 5))

        # Imagem Original com a linha marcada
        plt.subplot(1, 2, 1)
        plt.imshow(grayscale_original, cmap='gray')
        plt.axhline(y=row_idx, color='r', linestyle='-', linewidth=1)
        plt.title(f'Imagem Original (Linha {row_idx})')
        plt.axis('off')

        # Imagem Ruidosa com a linha marcada
        plt.subplot(1, 2, 2)
        plt.imshow(noisy_image, cmap='gray')
        plt.axhline(y=row_idx, color='r', linestyle='-', linewidth=1)
        plt.title(f'Imagem com Ruído (Linha {row_idx})')
        plt.axis('off')

        plt.tight_layout()
        plt.show()


# Chama a função principal
main()

"""# Exercício: Aplique o filtro de três pontos em todas as linhas da imagem e compare com o resultado da média das imagens da aula anterior."""

import matplotlib.pyplot as plt
import numpy as np
from skimage import data
from skimage.color import rgb2gray

def gera_ruido(original, noise_type="salt_pepper", noise_level=0.1):
    if len(original.shape) == 3:
        grayscale = rgb2gray(original)
    else:
        grayscale = original

    if noise_type == "gaussian":
        noise = np.random.normal(0, noise_level, grayscale.shape)
        grayscale_ruido = grayscale + noise
    else: # "salt_pepper"
        grayscale_ruido = grayscale.copy()
        p = noise_level
        rnd = np.random.rand(*grayscale.shape)
        grayscale_ruido[rnd < p / 2] = 0
        grayscale_ruido[rnd > 1 - p / 2] = 1

    grayscale_ruido = np.clip(grayscale_ruido, 0, 1)
    return grayscale_ruido

def filtroMedia3pontos(rowData):
    resultado = np.copy(rowData).astype(float)
    for i in range(1, len(rowData) - 1):
        media = (rowData[i-1] + rowData[i] + rowData[i+1]) / 3.0
        resultado[i] = media
    return resultado

def main():
    # 1. Preparação da imagem original
    original_image = data.camera() / 255.0

    # 2. Gerar uma única imagem com ruído (para o filtro espacial)
    noisy_image = gera_ruido(original_image, noise_type="gaussian", noise_level=0.1)

    # 3. Aplicar o filtro de 3 pontos em TODAS as linhas
    img_filtrada_espacial = np.zeros_like(noisy_image)
    for i in range(noisy_image.shape[0]):
        img_filtrada_espacial[i, :] = filtroMedia3pontos(noisy_image[i, :])

    # 4. Simular a "Média das Imagens" da aula anterior (Média Temporal)
    num_frames = 10
    soma_frames = np.zeros_like(original_image)
    for _ in range(num_frames):
        soma_frames += gera_ruido(original_image, noise_type="gaussian", noise_level=0.1)
    img_media_temporal = soma_frames / num_frames

    # --- Visualização dos Resultados ---
    plt.figure(figsize=(16, 8))

    plt.subplot(1, 3, 1)
    plt.imshow(noisy_image, cmap='gray')
    plt.title('1. Imagem com Ruído Original')
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.imshow(img_filtrada_espacial, cmap='gray')
    plt.title('2. Filtro de Média (3 pontos/Linha)\nFiltro Espacial')
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.imshow(img_media_temporal, cmap='gray')
    plt.title(f'3. Média de {num_frames} Imagens\nFiltro Temporal')
    plt.axis('off')

    plt.tight_layout()
    plt.show()

main()

"""---

## Aplicar o ruído e posteriormente o filtro apresentado no exemplo de aula às imagens do conjunto que você coletou. Compare com as imagens originais.

filtro = filtro Media 3 pontos
"""

import matplotlib.pyplot as plt
import numpy as np
from skimage import data
from skimage.color import rgb2gray
from skimage.io import imread
from skimage.transform import resize
from google.colab import files
from PIL import Image, ImageOps

def gera_ruido(original, noise_type="salt_pepper", noise_level=0.1):
    # Garante que a imagem esteja em escala de cinza e normalizada 0-1
    if len(original.shape) == 3:
        img_gray = rgb2gray(original)
    else:
        img_gray = original.astype(float)
        if img_gray.max() > 1.0:
            img_gray /= 255.0

    if noise_type == "gaussian":
        noise = np.random.normal(0, noise_level, img_gray.shape)
        img_ruido = img_gray + noise
    else: # "salt_pepper"
        img_ruido = img_gray.copy()
        p = noise_level
        rnd = np.random.rand(*img_gray.shape)
        img_ruido[rnd < p / 2] = 0
        img_ruido[rnd > 1 - p / 2] = 1

    return np.clip(img_ruido, 0, 1)

def filtroMedia3pontos(rowData):
    resultado = np.copy(rowData).astype(float)
    # Loop para percorrer a linha (filtro espacial 1D)
    for i in range(1, len(rowData) - 1):
        media = (rowData[i-1] + rowData[i] + rowData[i+1]) / 3.0
        resultado[i] = media
    return resultado

def aplicar_filtro_na_imagem(img_ruidosa):
    # Cria uma matriz vazia para o resultado
    img_filtrada = np.zeros_like(img_ruidosa)
    # Aplica linha por linha
    for r in range(img_ruidosa.shape[0]):
        img_filtrada[r, :] = filtroMedia3pontos(img_ruidosa[r, :])
    return img_filtrada

# 2. Carregador de dataset
def data_loader(target_height=512):
    print("Por favor, selecione as imagens do seu computador:")
    uploaded = files.upload()
    imagens = []

    for fname in uploaded.keys():
        img_pil = Image.open(fname)
        img_pil = ImageOps.exif_transpose(img_pil)
        img = np.array(img_pil)

        H, W = img.shape[:2]
        scale = target_height / H
        new_W = int(W * scale)

        img_resized = resize(
            img,
            (target_height, new_W),
            preserve_range=True,
            anti_aliasing=True
        ).astype(float) # Convertemos para float para os cálculos

        # Normalização para 0-1
        if img_resized.max() > 1.0:
            img_resized /= 255.0

        imagens.append(img_resized)

    print(f"{len(imagens)} imagens carregadas.")
    return imagens

# 3. Execução
def main():
    meu_dataset = data_loader()

    for i, img_original in enumerate(meu_dataset):
        # Converter para cinza se for colorida para o filtro funcionar
        if len(img_original.shape) == 3:
            img_gray = rgb2gray(img_original)
        else:
            img_gray = img_original

        # Adicionar ruído
        img_com_ruido = gera_ruido(img_gray, noise_type="salt_pepper", noise_level=0.1)

        # Aplicar o filtro de 3 pontos em todas as linhas
        img_recuperada = aplicar_filtro_na_imagem(img_com_ruido)

        # Comparação Visual
        plt.figure(figsize=(18, 6))

        plt.subplot(1, 3, 1)
        plt.imshow(img_gray, cmap='gray')
        plt.title(f"Imagem {i+1}: Original")
        plt.axis('off')

        plt.subplot(1, 3, 2)
        plt.imshow(img_com_ruido, cmap='gray')
        plt.title("Com Ruído")
        plt.axis('off')

        plt.subplot(1, 3, 3)
        plt.imshow(img_recuperada, cmap='gray')
        plt.title("Filtro Média 3-pontos (Linhas)")
        plt.axis('off')

        plt.tight_layout()
        plt.show()

main()